import "./styles/globals.css";
import SmoothScroll from "./components/SmoothScroll";
import Navbar from "./components/molecules/navbar/navbar";

export const metadata = {
  title: "Offcut",
  description: "Computer Generated by sebfok",
  icons:"/icons/RocksLogoRound.svg"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar />
        <div className='bodyWrap'>
          {/* <SmoothScroll> */}
          {/* removed because the sentinels wont fire immediatley. either make the sentinels a bit bigger but then that messes up timing*/}
          {children}
        {/* </SmoothScroll> */}
        </div>
      </body>
    </html>
  );
}
