import "./styles/globals.css";
import Navbar from "./components/molecules/navbar/navbar";

export const metadata = {
  title: "Offcut",
  description: "Computer Generated by sebfok",
  icons:"/icons/RocksLogoRound.svg"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar />
        <div className='bodyWrap'>
          {children}
        </div>
      </body>
    </html>
  );
}
