import "./styles/globals.css";
import SmoothScroll from "./components/SmoothScroll";
import Navbar from "./components/molecules/navbar/navbar";
import LockVh from "./hooks/LockVh";

export const metadata = {
  title: "Offcut",
  description: "Computer Generated by sebfok",
  icons:"/icons/RocksLogoRound.svg"
};

export default function RootLayout({ children }) {
  return (
    <LockVh>
      <html lang="en">
        <body suppressHydrationWarning={true}>
          <Navbar />
          <div className='bodyWrap'>
            {children}
          </div>
        </body>
      </html>
    </LockVh>
  );
}
